# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: GoRelease

on:
  push:
    tags: "*"
  schedule:
    - cron:  '0 0 1 * *'  # at start of every month - is workaround for 90-day artifact lifetime

jobs:

  build_arm64:
    runs-on: ubuntu-latest
    env:
        BIN_NAME: ncglpm_arm64
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build ARM64
      run: env GOOS=linux GOARCH=arm64 go build -v -o $BIN_NAME

    - name: Test
      run: go test -v ./...

    - name: Upload ARM64
      uses: actions/upload-artifact@v3
      with:
        name: $BIN_NAME
        path: $BIN_NAME

  build_amd64:
    runs-on: ubuntu-latest
    env:
        BIN_NAME: ncglpm_amd64
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build AMD64
      run: env GOOS=linux GOARCH=amd64 go build -v -o $BIN_NAME

    - name: Test
      run: go test -v ./...

    - name: Upload AMD64
      uses: actions/upload-artifact@v3
      with:
        name: $BIN_NAME
        path: $BIN_NAME

    