name: testBuild

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  testBuildOptionalUpload:
    permissions: write-all
    uses: ncgl-git/ncglpm/.github/workflows/_reusable_testBuildOptionalUpload.yml@main
    strategy:
      matrix:
        go_arch: [amd64]
        go_version: [1.18, 1.19]

    with:
      go_arch: ${{ matrix.go_arch }}
      go_version: ${{ matrix.go_version}}
      binary_prefix: 'ncglpm'
